


collections:
  standard:
    output: true
  serviceprofile:
    output: true
  profile:
    output: true
  capabilityprofile:
    output: true
  organisation:
    output: true


exclude: ['README.md','Gemfile','Gemfile.*','gulpfile.js','*.xsl','package.json','node_modules','vendor/bundle']
