


collections:
  standard:
    output: true
  bsp:
    output: true
  serviceprofile:
    output: true
  profile:
    output: true
  capabilityprofile:
    output: true
  organization:
    output: true
  responsibleparty:
    output: true
  node:
    output: true


exclude: ['README.md','Gemfile','Gemfile.*','gulpfile.js','package.json','node_modules','vendor/bundle','clean.sh']
