


collections:
  standard:
    output: true
  serviceprofile:
    output: true
  profile:
    output: true
  capabilityprofile:
    output: true

exclude: ['Gemfile.*','gulpfile.js','*.xsl','package.json','node_modules','vendor/bundle']
